[package]
name = "bstk-raft"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
serde.workspace = true
postcard.workspace = true
openraft.workspace = true
tokio.workspace = true
tracing.workspace = true
bstk-proto.workspace = true
bstk-engine.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
