[package]
name = "bstk-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
serde.workspace = true
bstk-proto.workspace = true

[dev-dependencies]
postcard.workspace = true
proptest.workspace = true
bstk-engine-oracle.workspace = true

[lints]
workspace = true
