//! Deterministic beanstalkd state machine.
//!
//! INTERFACE CONTRACT (owned by the lead): the public API in this file must
//! not change without lead approval.
//!
//! Rules: no system clock, no randomness, no I/O. Time is always passed in as
//! `now` (monotonic nanoseconds). Identical inputs must yield identical
//! outputs. Ground truth for semantics is `.ref/beanstalkd/{prot,job,tube,conn}.c`.

use bstk_proto::{Command, PutRejection, Response};

mod engine;
mod model;
mod ms;
#[cfg(test)]
mod oracle_tests;
#[cfg(test)]
mod recovery_tests;

pub use engine::Engine;

/// Monotonic time in nanoseconds, supplied by the caller.
pub type Nanos = u64;
/// Connection identifier, assigned by the caller; never reused within a process.
pub type ConnId = u64;

pub const NANOS_PER_SEC: Nanos = 1_000_000_000;

/// Replies produced by one engine call, in the order they must be delivered.
/// A single call can address several connections (e.g. a put waking a
/// waiting reserver). Each connection's replies must be written in order.
pub type Outbox = Vec<(ConnId, Response)>;

/// Process-level facts the engine cannot know itself (it has no I/O).
pub trait SysInfo: Send {
    fn snapshot(&self) -> SysSnapshot;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SysSnapshot {
    pub pid: u64,
    pub version: String,
    /// (seconds, microseconds)
    pub rusage_utime: (u64, u64),
    pub rusage_stime: (u64, u64),
    /// Random per-process id string (generated by the server at startup).
    pub id: String,
    pub hostname: String,
    pub os: String,
    pub platform: String,
}

/// Fixed `SysInfo` for tests.
#[derive(Debug, Clone, Default)]
pub struct StaticSysInfo(pub SysSnapshot);

impl SysInfo for StaticSysInfo {
    fn snapshot(&self) -> SysSnapshot {
        self.0.clone()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct EngineConfig {
    /// `-z`; reported as `max-job-size` in stats. (Size enforcement happens in
    /// the codec.)
    pub max_job_size: u32,
    /// `-s`; reported as `binlog-max-size` in stats. The reference reports
    /// its default even when the binlog is disabled.
    pub binlog_max_size: u64,
    /// Record journal entries at the reference's binlog transitions (`-b`).
    /// When false, `take_journal` always yields nothing.
    pub journal: bool,
}

/// Default binlog file size (`Filesizedef` in dat.h).
pub const DEFAULT_BINLOG_MAX_SIZE: u64 = 10 << 20;

impl Default for EngineConfig {
    fn default() -> Self {
        EngineConfig {
            max_job_size: bstk_proto::DEFAULT_MAX_JOB_SIZE,
            binlog_max_size: DEFAULT_BINLOG_MAX_SIZE,
            journal: false,
        }
    }
}

/// Persistent job state as of a journaled transition (the reference's
/// `Jobrec`). Times are engine `Nanos`, which the server anchors to the wall
/// clock so they stay meaningful across restarts.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct JobRecord {
    pub id: bstk_proto::JobId,
    pub pri: u32,
    /// Delay in whole seconds, as last set by put or release.
    pub delay: u32,
    /// TTR in whole seconds (already bumped from 0 to 1).
    pub ttr: u32,
    pub created_at: Nanos,
    /// When a delayed job becomes ready; 0 for other states.
    pub deadline_at: Nanos,
    pub state: RecordState,
    pub reserve_ct: u32,
    pub timeout_ct: u32,
    pub release_ct: u32,
    pub bury_ct: u32,
    pub kick_ct: u32,
}

/// Job state in a journal record. A reserved job is never journaled as
/// such (reserve is not a journaled transition).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RecordState {
    Ready,
    Delayed,
    Buried,
}

/// One binlog record, emitted at exactly the transitions the reference
/// writes (see docs/PLAN.md §4.1). The last record of a job wins on replay.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum JournalEntry {
    /// The job's first record: full state plus tube and body.
    Put {
        record: JobRecord,
        tube: bstk_proto::TubeName,
        body: bytes::Bytes,
    },
    /// A later transition (release with delay, bury, kick, kick-job).
    Update(JobRecord),
    /// The job was deleted.
    Delete(bstk_proto::JobId),
}

/// A job rebuilt from the binlog, in its final journaled state.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RecoveredJob {
    pub record: JobRecord,
    pub tube: bstk_proto::TubeName,
    pub body: bytes::Bytes,
}

/// What the store hands to `Engine::recover`.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Recovery {
    /// Live jobs in the reference's replay order (order of each job's first
    /// surviving record).
    pub jobs: Vec<RecoveredJob>,
    /// Highest job id in any surviving record (live or deleted) + 1, and at
    /// least 1.
    pub next_id: bstk_proto::JobId,
    /// Tube list order the reference ends up with after replaying every
    /// surviving record in file order, excluding `default` (always first):
    /// a tube is appended when a job's full record first needs it, and
    /// swap-removed (`ms_remove`) when a delete record frees its last job.
    /// Tubes without live jobs are ignored; tubes of live jobs missing here
    /// are appended in first-appearance order.
    pub tube_order: Vec<bstk_proto::TubeName>,
}

/// Binlog fields of `stats`, owned by the store.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct BinlogStats {
    pub oldest_index: u64,
    pub current_index: u64,
    pub records_written: u64,
    pub records_migrated: u64,
}

/// Point-in-time view for monitoring (`Engine::snapshot`,
/// `Engine::snapshot_limited`). Taking it has no
/// side effects: no counter (e.g. `cmd-stats`) changes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Snapshot {
    /// Exactly what `stats` would report at the same `now`.
    pub server: bstk_proto::StatsServer,
    /// What `stats-tube` would report for every tube, in `list-tubes` order.
    pub tubes: Vec<bstk_proto::StatsTube>,
}

/// One engine input, as replicated through the Raft log in cluster mode
/// (P3). `Engine::apply_input` maps each variant onto the matching method
/// and then runs `tick(now)`, so replaying the same inputs with the same
/// `now` values yields the same state and replies on every node.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum EngineInput {
    Connect(ConnId),
    Disconnect(ConnId),
    HalfClose(ConnId),
    PutStarted {
        conn: ConnId,
        too_big: bool,
    },
    PutRejected {
        conn: ConnId,
        why: PutRejection,
    },
    /// `Command::Quit` is never sent (the server handles it).
    Command {
        conn: ConnId,
        cmd: Command,
    },
    /// Time-driven transitions only (delays, TTRs, timeouts, pauses).
    Tick,
    SetDraining(bool),
}

impl EngineInput {
    /// The connection this input belongs to, if any.
    pub fn conn(&self) -> Option<ConnId> {
        match self {
            EngineInput::Connect(c) | EngineInput::Disconnect(c) | EngineInput::HalfClose(c) => {
                Some(*c)
            }
            EngineInput::PutStarted { conn, .. }
            | EngineInput::PutRejected { conn, .. }
            | EngineInput::Command { conn, .. } => Some(*conn),
            EngineInput::Tick | EngineInput::SetDraining(_) => None,
        }
    }
}

/// The complete engine state (P3 Raft snapshots): everything except the
/// `SysInfo` handle and the (always empty in cluster mode) journal. Opaque;
/// only produced by `Engine::export_state` and consumed by
/// `Engine::import_state`. Importing and continuing must be
/// indistinguishable from never having exported.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EngineState {
    // Filled in by P3-T1.
    pub(crate) _todo: (),
}

/// `Engine::import_state` rejected a state that violates engine
/// invariants (corrupt or hostile snapshot).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StateError(pub String);

impl std::fmt::Display for StateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "invalid engine state: {}", self.0)
    }
}

impl std::error::Error for StateError {}

/// Public API surface (implemented in `engine.rs`):
///
/// ```ignore
/// impl Engine {
///     pub fn new(now: Nanos, cfg: EngineConfig, sys: Box<dyn SysInfo>) -> Self;
///     /// Register a new connection (uses and watches "default").
///     pub fn connect(&mut self, now: Nanos, conn: ConnId);
///     /// Connection closed: release its reserved jobs, drop it from wait
///     /// queues, deref tubes. Never produces replies for `conn`, but may
///     /// produce replies for others (released jobs can wake waiters).
///     pub fn disconnect(&mut self, now: Nanos, conn: ConnId, out: &mut Outbox);
///     /// Client half-closed its socket: if `conn` is waiting on reserve,
///     /// reply TIMED_OUT (see STATE_WAIT / halfclosed in prot.c).
///     pub fn half_close(&mut self, now: Nanos, conn: ConnId, out: &mut Outbox);
///     /// A put command line was accepted (`Frame::PutStarted`): applies the
///     /// reference's header-time side effects (cmd-put, producer, job id)
///     /// before the body arrives. No reply.
///     pub fn put_started(&mut self, now: Nanos, conn: ConnId, too_big: bool);
///     /// A `put` rejected by the codec (`Frame::PutRejected`): applies the
///     /// reference's pre-rejection side effects and emits the reply.
///     pub fn put_rejected(&mut self, now: Nanos, conn: ConnId, why: PutRejection, out: &mut Outbox);
///     /// Execute one command. `Command::Quit` is handled by the server and
///     /// must not be passed here. A reserve that must wait produces no reply
///     /// now; the reply is emitted by a later call (handle/tick/disconnect).
///     /// Callers must not send another command for `conn` until it has
///     /// received the reply to the previous one.
///     pub fn handle(&mut self, now: Nanos, conn: ConnId, cmd: Command, out: &mut Outbox);
///     /// Process everything due at or before `now` (delays, TTRs,
///     /// DEADLINE_SOON, reserve timeouts, pause expiry).
///     pub fn tick(&mut self, now: Nanos, out: &mut Outbox);
///     /// Earliest time `tick` must be called, if any.
///     pub fn next_deadline(&self) -> Option<Nanos>;
///     /// Rebuild state after a restart from the binlog (docs/PLAN.md §4.1):
///     /// reserved jobs were never journaled as such; delayed jobs whose
///     /// deadline has passed become ready; replaying a buried job counts
///     /// one more bury; cumulative counters start at zero; recovered jobs
///     /// don't count toward `total-jobs`. Emits no journal entries.
///     pub fn recover(now: Nanos, cfg: EngineConfig, sys: Box<dyn SysInfo>, recovery: Recovery) -> Self;
///     /// Move all pending journal entries into `buf` (appending, in order).
///     pub fn take_journal(&mut self, buf: &mut Vec<JournalEntry>);
///     /// Binlog fields reported by `stats`, pushed by the server after
///     /// every binlog write.
///     pub fn set_binlog_stats(&mut self, stats: BinlogStats);
///     /// Monitoring view; see `Snapshot`. Never changes engine state.
///     pub fn snapshot(&self, now: Nanos) -> Snapshot;
///     /// Same, with only the first `max_tubes` tubes (in `list-tubes`
///     /// order); the server stats are complete. Bounds the work per call.
///     pub fn snapshot_limited(&self, now: Nanos, max_tubes: usize) -> Snapshot;
///     /// SIGUSR1 drain mode (put -> DRAINING).
///     pub fn set_draining(&mut self, on: bool);
///     /// P3: run one input (see `EngineInput`), then `tick(now)`.
///     pub fn apply_input(&mut self, now: Nanos, input: EngineInput, out: &mut Outbox);
///     /// P3: ids of all connections, ascending.
///     pub fn conn_ids(&self) -> Vec<ConnId>;
///     pub fn config(&self) -> &EngineConfig;
///     /// P3: full state for a snapshot; no side effects.
///     pub fn export_state(&self) -> EngineState;
///     /// P3: rebuild from a snapshot, validating every invariant
///     /// (indexes, counters, references); never panics on bad input.
///     pub fn import_state(state: EngineState, sys: Box<dyn SysInfo>) -> Result<Engine, StateError>;
/// }
/// ```
#[doc(hidden)]
pub fn _api_doc() {}
