//! Deterministic beanstalkd state machine.
//!
//! INTERFACE CONTRACT (owned by the lead): the public API in this file must
//! not change without lead approval.
//!
//! Rules: no system clock, no randomness, no I/O. Time is always passed in as
//! `now` (monotonic nanoseconds). Identical inputs must yield identical
//! outputs. Ground truth for semantics is `.ref/beanstalkd/{prot,job,tube,conn}.c`.

use bstk_proto::Response;

mod engine;
mod model;
mod ms;

pub use engine::Engine;

/// Monotonic time in nanoseconds, supplied by the caller.
pub type Nanos = u64;
/// Connection identifier, assigned by the caller; never reused within a process.
pub type ConnId = u64;

pub const NANOS_PER_SEC: Nanos = 1_000_000_000;

/// Replies produced by one engine call, in the order they must be delivered.
/// A single call can address several connections (e.g. a put waking a
/// waiting reserver). Each connection's replies must be written in order.
pub type Outbox = Vec<(ConnId, Response)>;

/// Process-level facts the engine cannot know itself (it has no I/O).
pub trait SysInfo: Send {
    fn snapshot(&self) -> SysSnapshot;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SysSnapshot {
    pub pid: u64,
    pub version: String,
    /// (seconds, microseconds)
    pub rusage_utime: (u64, u64),
    pub rusage_stime: (u64, u64),
    /// Random per-process id string (generated by the server at startup).
    pub id: String,
    pub hostname: String,
    pub os: String,
    pub platform: String,
}

/// Fixed `SysInfo` for tests.
#[derive(Debug, Clone, Default)]
pub struct StaticSysInfo(pub SysSnapshot);

impl SysInfo for StaticSysInfo {
    fn snapshot(&self) -> SysSnapshot {
        self.0.clone()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EngineConfig {
    /// `-z`; reported as `max-job-size` in stats. (Size enforcement happens in
    /// the codec.)
    pub max_job_size: u32,
    /// `-s`; reported as `binlog-max-size` in stats. The reference reports
    /// its default even when the binlog is disabled.
    pub binlog_max_size: u64,
}

/// Default binlog file size (`Filesizedef` in dat.h).
pub const DEFAULT_BINLOG_MAX_SIZE: u64 = 10 << 20;

impl Default for EngineConfig {
    fn default() -> Self {
        EngineConfig {
            max_job_size: bstk_proto::DEFAULT_MAX_JOB_SIZE,
            binlog_max_size: DEFAULT_BINLOG_MAX_SIZE,
        }
    }
}

/// Public API surface (implemented in `engine.rs`):
///
/// ```ignore
/// impl Engine {
///     pub fn new(now: Nanos, cfg: EngineConfig, sys: Box<dyn SysInfo>) -> Self;
///     /// Register a new connection (uses and watches "default").
///     pub fn connect(&mut self, now: Nanos, conn: ConnId);
///     /// Connection closed: release its reserved jobs, drop it from wait
///     /// queues, deref tubes. Never produces replies for `conn`, but may
///     /// produce replies for others (released jobs can wake waiters).
///     pub fn disconnect(&mut self, now: Nanos, conn: ConnId, out: &mut Outbox);
///     /// Client half-closed its socket: if `conn` is waiting on reserve,
///     /// reply TIMED_OUT (see STATE_WAIT / halfclosed in prot.c).
///     pub fn half_close(&mut self, now: Nanos, conn: ConnId, out: &mut Outbox);
///     /// A put command line was accepted (`Frame::PutStarted`): applies the
///     /// reference's header-time side effects (cmd-put, producer, job id)
///     /// before the body arrives. No reply.
///     pub fn put_started(&mut self, now: Nanos, conn: ConnId, too_big: bool);
///     /// A `put` rejected by the codec (`Frame::PutRejected`): applies the
///     /// reference's pre-rejection side effects and emits the reply.
///     pub fn put_rejected(&mut self, now: Nanos, conn: ConnId, why: PutRejection, out: &mut Outbox);
///     /// Execute one command. `Command::Quit` is handled by the server and
///     /// must not be passed here. A reserve that must wait produces no reply
///     /// now; the reply is emitted by a later call (handle/tick/disconnect).
///     /// Callers must not send another command for `conn` until it has
///     /// received the reply to the previous one.
///     pub fn handle(&mut self, now: Nanos, conn: ConnId, cmd: Command, out: &mut Outbox);
///     /// Process everything due at or before `now` (delays, TTRs,
///     /// DEADLINE_SOON, reserve timeouts, pause expiry).
///     pub fn tick(&mut self, now: Nanos, out: &mut Outbox);
///     /// Earliest time `tick` must be called, if any.
///     pub fn next_deadline(&self) -> Option<Nanos>;
///     /// SIGUSR1 drain mode (put -> DRAINING).
///     pub fn set_draining(&mut self, on: bool);
/// }
/// ```
#[doc(hidden)]
pub fn _api_doc() {}
