//! Deterministic beanstalkd state machine.
//!
//! The public API here is the interface contract with the server and the
//! Raft layer: change it only with the lead's approval.
//!
//! Rules: no system clock, no randomness, no I/O. Time is always passed in as
//! `now` (monotonic nanoseconds). Identical inputs must yield identical
//! outputs. Ground truth for semantics is `.ref/beanstalkd/{prot,job,tube,conn}.c`.

use bstk_proto::{Command, PutRejection, Response};

mod engine;
mod model;
mod ms;
#[cfg(test)]
mod oracle_tests;
#[cfg(test)]
mod recovery_tests;
#[cfg(test)]
mod scale_tests;
#[cfg(test)]
mod state_tests;

pub use engine::Engine;

/// Monotonic time in nanoseconds, supplied by the caller.
pub type Nanos = u64;
/// Connection identifier, assigned by the caller; never reused within a process.
pub type ConnId = u64;

pub const NANOS_PER_SEC: Nanos = 1_000_000_000;

/// Replies produced by one engine call, in the order they must be delivered.
/// A single call can address several connections (e.g. a put waking a
/// waiting reserver). Each connection's replies must be written in order.
pub type Outbox = Vec<(ConnId, Response)>;

/// The connections whose replies this process delivers: those with
/// `conn >> node_shift == node` (the cluster numbers a connection by its
/// owner). See `Engine::set_local_conns`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LocalConns {
    node_shift: u32,
    node: u64,
}

impl LocalConns {
    pub fn new(node_shift: u32, node: u64) -> Self {
        debug_assert!(node_shift < u64::BITS);
        LocalConns { node_shift, node }
    }

    pub fn owns(&self, conn: ConnId) -> bool {
        conn >> self.node_shift == self.node
    }
}

/// Process-level facts the engine cannot know itself (it has no I/O).
pub trait SysInfo: Send {
    fn snapshot(&self) -> SysSnapshot;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SysSnapshot {
    pub pid: u64,
    pub version: String,
    /// (seconds, microseconds)
    pub rusage_utime: (u64, u64),
    pub rusage_stime: (u64, u64),
    /// Random per-process id string (generated by the server at startup).
    pub id: String,
    pub hostname: String,
    pub os: String,
    pub platform: String,
}

#[derive(Debug, Clone, Default)]
pub struct StaticSysInfo(pub SysSnapshot);

impl SysInfo for StaticSysInfo {
    fn snapshot(&self) -> SysSnapshot {
        self.0.clone()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct EngineConfig {
    /// `-z`; reported as `max-job-size` in stats. (Size enforcement happens in
    /// the codec.)
    pub max_job_size: u32,
    /// `-s`; reported as `binlog-max-size` in stats. The reference reports
    /// its default even when the binlog is disabled.
    pub binlog_max_size: u64,
    /// Record journal entries at the reference's binlog transitions (`-b`).
    /// When false, `take_journal` always yields nothing.
    pub journal: bool,
}

/// Default binlog file size (`Filesizedef` in dat.h).
pub const DEFAULT_BINLOG_MAX_SIZE: u64 = 10 << 20;

impl Default for EngineConfig {
    fn default() -> Self {
        EngineConfig {
            max_job_size: bstk_proto::DEFAULT_MAX_JOB_SIZE,
            binlog_max_size: DEFAULT_BINLOG_MAX_SIZE,
            journal: false,
        }
    }
}

/// Persistent job state as of a journaled transition (the reference's
/// `Jobrec`). Times are engine `Nanos`, which the server anchors to the wall
/// clock so they stay meaningful across restarts.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct JobRecord {
    pub id: bstk_proto::JobId,
    pub pri: u32,
    /// Delay in whole seconds, as last set by put or release.
    pub delay: u32,
    /// TTR in whole seconds (already bumped from 0 to 1).
    pub ttr: u32,
    pub created_at: Nanos,
    /// When a delayed job becomes ready; 0 for other states.
    pub deadline_at: Nanos,
    pub state: RecordState,
    pub reserve_ct: u32,
    pub timeout_ct: u32,
    pub release_ct: u32,
    pub bury_ct: u32,
    pub kick_ct: u32,
}

/// Job state in a journal record. A reserved job is never journaled as
/// such (reserve is not a journaled transition).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RecordState {
    Ready,
    Delayed,
    Buried,
}

/// One binlog record, emitted at exactly the transitions the reference
/// writes (see docs/PLAN.md §4.1). The last record of a job wins on replay.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum JournalEntry {
    Put {
        record: JobRecord,
        tube: bstk_proto::TubeName,
        body: bytes::Bytes,
    },
    Update(JobRecord),
    Delete(bstk_proto::JobId),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RecoveredJob {
    pub record: JobRecord,
    pub tube: bstk_proto::TubeName,
    pub body: bytes::Bytes,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Recovery {
    /// Live jobs in the reference's replay order (order of each job's first
    /// surviving record).
    pub jobs: Vec<RecoveredJob>,
    /// Highest job id in any surviving record (live or deleted) + 1, and at
    /// least 1.
    pub next_id: bstk_proto::JobId,
    /// Tube list order the reference ends up with after replaying every
    /// surviving record in file order, excluding `default` (always first):
    /// a tube is appended when a job's full record first needs it, and
    /// swap-removed (`ms_remove`) when a delete record frees its last job.
    /// Tubes without live jobs are ignored; tubes of live jobs missing here
    /// are appended in first-appearance order.
    pub tube_order: Vec<bstk_proto::TubeName>,
}

/// Binlog fields of `stats`, owned by the store.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, serde::Serialize, serde::Deserialize)]
pub struct BinlogStats {
    pub oldest_index: u64,
    pub current_index: u64,
    pub records_written: u64,
    pub records_migrated: u64,
}

/// Point-in-time view for monitoring (`Engine::snapshot`,
/// `Engine::snapshot_limited`). Taking it has no
/// side effects: no counter (e.g. `cmd-stats`) changes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Snapshot {
    /// Exactly what `stats` would report at the same `now`.
    pub server: bstk_proto::StatsServer,
    /// What `stats-tube` would report for every tube, in `list-tubes` order.
    pub tubes: Vec<bstk_proto::StatsTube>,
}

/// One engine input, as replicated through the Raft log in cluster mode
/// (P3). `Engine::apply_input` maps each variant onto the matching method
/// and then runs `tick(now)`, so replaying the same inputs with the same
/// `now` values yields the same state and replies on every node.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum EngineInput {
    Connect(ConnId),
    Disconnect(ConnId),
    HalfClose(ConnId),
    PutStarted {
        conn: ConnId,
        too_big: bool,
    },
    PutRejected {
        conn: ConnId,
        why: PutRejection,
    },
    /// `Command::Quit` is never sent (the server handles it).
    Command {
        conn: ConnId,
        cmd: Command,
    },
    /// Time-driven transitions only (delays, TTRs, timeouts, pauses).
    Tick,
    SetDraining(bool),
}

impl EngineInput {
    pub fn conn(&self) -> Option<ConnId> {
        match self {
            EngineInput::Connect(c) | EngineInput::Disconnect(c) | EngineInput::HalfClose(c) => {
                Some(*c)
            }
            EngineInput::PutStarted { conn, .. }
            | EngineInput::PutRejected { conn, .. }
            | EngineInput::Command { conn, .. } => Some(*conn),
            EngineInput::Tick | EngineInput::SetDraining(_) => None,
        }
    }
}

/// The complete engine state (P3 Raft snapshots): everything except the
/// `SysInfo` handle and the (always empty in cluster mode) journal. Opaque;
/// only produced by `Engine::export_state` and consumed by
/// `Engine::import_state`. Importing and continuing must be
/// indistinguishable from never having exported.
///
/// It mirrors `Engine` field by field. Maps are stored as vectors sorted by
/// key, so equal states serialize to identical bytes on every node.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct EngineState {
    pub(crate) cfg: EngineConfig,
    pub(crate) start: Nanos,
    pub(crate) draining: bool,

    pub(crate) next_job_id: bstk_proto::JobId,
    /// Sorted by id (strictly ascending). Boxed as in `Engine`, so
    /// `import_state` moves each record instead of copying it, and a
    /// decoded state holds no second copy of the job table (serde encodes
    /// a `Box` as its contents, so the bytes are those of the records).
    #[allow(clippy::vec_box)]
    pub(crate) jobs: Vec<Box<model::JobRec>>,
    /// Next key for `TubeState::buried` / `ConnState::reserved`.
    pub(crate) next_list_seq: u64,

    pub(crate) tubes: Vec<Option<model::TubeState>>,
    pub(crate) free_tube_ids: Vec<model::TubeId>,
    /// Sorted by name (strictly ascending).
    pub(crate) tube_ids: Vec<(bstk_proto::TubeName, model::TubeId)>,
    pub(crate) tube_order: ms::Ms<model::TubeId>,

    /// Sorted by id (strictly ascending).
    pub(crate) conns: Vec<(ConnId, model::ConnState)>,

    pub(crate) conn_ticks: std::collections::BTreeSet<(Nanos, ConnId)>,
    pub(crate) delay_heads: std::collections::BTreeSet<(Nanos, model::TubeId)>,
    pub(crate) pauses: std::collections::BTreeSet<(Nanos, model::TubeId)>,
    pub(crate) dispatchable: std::collections::BTreeSet<model::TubeId>,

    pub(crate) ready_ct: u64,
    pub(crate) urgent_ct: u64,
    pub(crate) reserved_ct: u64,
    pub(crate) buried_ct: u64,
    pub(crate) delayed_ct: u64,
    pub(crate) waiting_ct: u64,
    pub(crate) total_jobs_ct: u64,
    pub(crate) timeout_ct: u64,

    pub(crate) cur_conns: u32,
    pub(crate) tot_conns: u32,
    pub(crate) cur_producers: u32,
    pub(crate) cur_workers: u32,

    pub(crate) cmd_put: u64,
    pub(crate) cmd_peek: u64,
    pub(crate) cmd_peek_ready: u64,
    pub(crate) cmd_peek_delayed: u64,
    pub(crate) cmd_peek_buried: u64,
    pub(crate) cmd_reserve: u64,
    pub(crate) cmd_reserve_with_timeout: u64,
    pub(crate) cmd_delete: u64,
    pub(crate) cmd_release: u64,
    pub(crate) cmd_use: u64,
    pub(crate) cmd_watch: u64,
    pub(crate) cmd_ignore: u64,
    pub(crate) cmd_bury: u64,
    pub(crate) cmd_kick: u64,
    pub(crate) cmd_touch: u64,
    pub(crate) cmd_stats: u64,
    pub(crate) cmd_stats_job: u64,
    pub(crate) cmd_stats_tube: u64,
    pub(crate) cmd_list_tubes: u64,
    pub(crate) cmd_list_tube_used: u64,
    pub(crate) cmd_list_tubes_watched: u64,
    pub(crate) cmd_pause_tube: u64,

    pub(crate) binlog: BinlogStats,
}

/// A borrowed view of the engine state that serializes to exactly the
/// bytes of `Engine::export_state` (P4-T5c streamed snapshots, docs/DESIGN.md
/// §8): the state machine encodes snapshots from it, so no copy of the
/// state is made. Opaque; produced by `Engine::state_view`.
#[derive(Debug, serde::Serialize)]
pub struct EngineStateView<'a> {
    pub(crate) cfg: &'a EngineConfig,
    pub(crate) start: Nanos,
    pub(crate) draining: bool,

    pub(crate) next_job_id: bstk_proto::JobId,
    pub(crate) jobs: Vec<&'a model::JobRec>,
    pub(crate) next_list_seq: u64,

    pub(crate) tubes: &'a [Option<model::TubeState>],
    pub(crate) free_tube_ids: &'a [model::TubeId],
    pub(crate) tube_ids: Vec<(&'a bstk_proto::TubeName, model::TubeId)>,
    pub(crate) tube_order: &'a ms::Ms<model::TubeId>,

    pub(crate) conns: Vec<(ConnId, &'a model::ConnState)>,

    pub(crate) conn_ticks: &'a std::collections::BTreeSet<(Nanos, ConnId)>,
    pub(crate) delay_heads: &'a std::collections::BTreeSet<(Nanos, model::TubeId)>,
    pub(crate) pauses: &'a std::collections::BTreeSet<(Nanos, model::TubeId)>,
    pub(crate) dispatchable: &'a std::collections::BTreeSet<model::TubeId>,

    pub(crate) ready_ct: u64,
    pub(crate) urgent_ct: u64,
    pub(crate) reserved_ct: u64,
    pub(crate) buried_ct: u64,
    pub(crate) delayed_ct: u64,
    pub(crate) waiting_ct: u64,
    pub(crate) total_jobs_ct: u64,
    pub(crate) timeout_ct: u64,

    pub(crate) cur_conns: u32,
    pub(crate) tot_conns: u32,
    pub(crate) cur_producers: u32,
    pub(crate) cur_workers: u32,

    pub(crate) cmd_put: u64,
    pub(crate) cmd_peek: u64,
    pub(crate) cmd_peek_ready: u64,
    pub(crate) cmd_peek_delayed: u64,
    pub(crate) cmd_peek_buried: u64,
    pub(crate) cmd_reserve: u64,
    pub(crate) cmd_reserve_with_timeout: u64,
    pub(crate) cmd_delete: u64,
    pub(crate) cmd_release: u64,
    pub(crate) cmd_use: u64,
    pub(crate) cmd_watch: u64,
    pub(crate) cmd_ignore: u64,
    pub(crate) cmd_bury: u64,
    pub(crate) cmd_kick: u64,
    pub(crate) cmd_touch: u64,
    pub(crate) cmd_stats: u64,
    pub(crate) cmd_stats_job: u64,
    pub(crate) cmd_stats_tube: u64,
    pub(crate) cmd_list_tubes: u64,
    pub(crate) cmd_list_tube_used: u64,
    pub(crate) cmd_list_tubes_watched: u64,
    pub(crate) cmd_pause_tube: u64,

    pub(crate) binlog: BinlogStats,
}

/// `Engine::import_state` rejected a state that violates engine
/// invariants (corrupt or hostile snapshot).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StateError(pub String);

impl std::fmt::Display for StateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "invalid engine state: {}", self.0)
    }
}

impl std::error::Error for StateError {}
