//! FROZEN ORACLE: a verbatim copy of `bstk-engine` as of commit 4304ef6
//! (before the T6b performance work), used only as a dev-dependency of
//! `bstk-engine`. Its differential proptest feeds this engine and the
//! optimized one identical `(now, message)` sequences and requires
//! identical outboxes, deadlines and stats. Do not change its behavior:
//! the only edits vs. the original are removed test modules, comments trimmed
//! (P4-T8) and the stats builders made `pub` for that comparison.
//!
//! Rules: no system clock, no randomness, no I/O. Time is always passed in as
//! `now` (monotonic nanoseconds). Identical inputs must yield identical
//! outputs. Ground truth for semantics is `.ref/beanstalkd/{prot,job,tube,conn}.c`.

use bstk_proto::Response;

mod engine;
mod model;
mod ms;

pub use engine::Engine;

/// Monotonic time in nanoseconds, supplied by the caller.
pub type Nanos = u64;
/// Connection identifier, assigned by the caller; never reused within a process.
pub type ConnId = u64;

pub const NANOS_PER_SEC: Nanos = 1_000_000_000;

/// Replies produced by one engine call, in the order they must be delivered.
/// A single call can address several connections (e.g. a put waking a
/// waiting reserver). Each connection's replies must be written in order.
pub type Outbox = Vec<(ConnId, Response)>;

/// Process-level facts the engine cannot know itself (it has no I/O).
pub trait SysInfo: Send {
    fn snapshot(&self) -> SysSnapshot;
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SysSnapshot {
    pub pid: u64,
    pub version: String,
    /// (seconds, microseconds)
    pub rusage_utime: (u64, u64),
    pub rusage_stime: (u64, u64),
    /// Random per-process id string (generated by the server at startup).
    pub id: String,
    pub hostname: String,
    pub os: String,
    pub platform: String,
}

#[derive(Debug, Clone, Default)]
pub struct StaticSysInfo(pub SysSnapshot);

impl SysInfo for StaticSysInfo {
    fn snapshot(&self) -> SysSnapshot {
        self.0.clone()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EngineConfig {
    /// `-z`; reported as `max-job-size` in stats. (Size enforcement happens in
    /// the codec.)
    pub max_job_size: u32,
    /// `-s`; reported as `binlog-max-size` in stats. The reference reports
    /// its default even when the binlog is disabled.
    pub binlog_max_size: u64,
}

/// Default binlog file size (`Filesizedef` in dat.h).
pub const DEFAULT_BINLOG_MAX_SIZE: u64 = 10 << 20;

impl Default for EngineConfig {
    fn default() -> Self {
        EngineConfig {
            max_job_size: bstk_proto::DEFAULT_MAX_JOB_SIZE,
            binlog_max_size: DEFAULT_BINLOG_MAX_SIZE,
        }
    }
}
