[package]
name = "bstk-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
bstk-proto.workspace = true
bstk-engine.workspace = true
crc32c = "0.6.8"
tracing.workspace = true
nix = { version = "0.29", features = ["fs"] }

[dev-dependencies]
proptest.workspace = true
tempfile = "3.27.0"

[lints]
workspace = true
