//! Spawning and lifecycle management of a server binary under test.
//!
//! A server is exposed to the harness over one of three transports
//! ([`ServerTransport`]):
//!
//! - `Plain`: started with `-l 127.0.0.1 -p <port>`; plaintext clients.
//! - `Tls`: started with `--config <file>` (plus the other arguments), where
//!   the generated TOML file declares exactly one TLS listener on the
//!   server's port and points at the harness's throwaway certificate (see
//!   [`crate::tls`]). `-l` / `-p` are not passed: they cannot be combined
//!   with `[[listener]]`. Clients connect over TLS.
//! - `Stunnel`: the server runs plaintext on a private backend port and a
//!   `stunnel` process terminates TLS on the public port, forwarding to it.
//!   Clients connect over TLS. This validates the harness's TLS path with a
//!   server that has no TLS support of its own (the reference).

use std::collections::HashSet;
use std::net::{SocketAddr, TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::{Arc, LazyLock, Mutex};
use std::time::{Duration, Instant};

use crate::conn::ClientTransport;
use crate::dsl::StopMode;
use crate::tls::{TlsMaterial, create_temp_dir};

const STARTUP_TIMEOUT: Duration = Duration::from_secs(5);
const STOP_TIMEOUT: Duration = Duration::from_secs(5);
const SPAWN_ATTEMPTS: u32 = 3;

/// Ports currently claimed by a `ServerProcess` somewhere in this process.
///
/// `TcpListener::bind(("127.0.0.1", 0))` picks an OS-assigned free port, but
/// there is a gap between releasing that listener and the child process
/// actually binding the same port. Under this harness's parallel case
/// runner, two worker threads can race and get handed the *same* ephemeral
/// port in that gap, causing two unrelated cases to collide on one server.
/// This registry closes that race within our own process: a port is held
/// for the entire lifetime of the `ServerProcess`, not just during spawn.
static CLAIMED_PORTS: LazyLock<Mutex<HashSet<u16>>> = LazyLock::new(|| Mutex::new(HashSet::new()));

fn claim_free_port() -> std::io::Result<u16> {
    loop {
        let listener = TcpListener::bind(("127.0.0.1", 0))?;
        let port = listener.local_addr()?.port();
        drop(listener);
        let mut claimed = CLAIMED_PORTS.lock().expect("claimed-ports lock poisoned");
        if claimed.insert(port) {
            return Ok(port);
        }
        // Another case in this process already claimed this exact port
        // (extremely unlikely, but cheap to retry); pick another one.
    }
}

fn release_port(port: u16) {
    CLAIMED_PORTS
        .lock()
        .expect("claimed-ports lock poisoned")
        .remove(&port);
}

/// A temporary directory, removed (recursively) on drop.
#[derive(Debug)]
pub struct TempDir {
    path: PathBuf,
}

/// A per-server temporary binlog directory.
pub type BinlogDir = TempDir;

impl TempDir {
    /// Create a fresh, empty binlog directory under the system temp
    /// directory.
    pub fn create() -> std::io::Result<Self> {
        Self::with_prefix("bstk-compat-binlog")
    }

    /// Create a fresh, empty directory `<tmp>/<prefix>-<pid>-<n>`.
    pub fn with_prefix(prefix: &str) -> std::io::Result<Self> {
        Ok(TempDir {
            path: create_temp_dir(prefix)?,
        })
    }

    pub fn path(&self) -> &Path {
        &self.path
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.path);
    }
}

/// How a server is exposed to the harness (see the module docs).
#[derive(Debug, Clone, Default)]
pub enum ServerTransport {
    /// Plaintext on `-l 127.0.0.1 -p <port>`.
    #[default]
    Plain,
    /// The server itself serves TLS, configured through a generated
    /// `--config` file with one TLS listener.
    Tls(Arc<TlsMaterial>),
    /// The server serves plaintext on a backend port; `stunnel` (at the
    /// given path) terminates TLS on the public port.
    Stunnel {
        stunnel: PathBuf,
        material: Arc<TlsMaterial>,
    },
}

impl ServerTransport {
    /// How clients connect to a server exposed this way.
    pub fn client(&self) -> ClientTransport {
        match self {
            ServerTransport::Plain => ClientTransport::Plain,
            ServerTransport::Tls(m) | ServerTransport::Stunnel { material: m, .. } => {
                ClientTransport::Tls(m.client_config())
            }
        }
    }
}

/// The TOML configuration file for a server with one TLS listener on
/// `port`, using the certificate and key of `material`.
pub fn tls_server_config(port: u16, material: &TlsMaterial) -> String {
    format!(
        "# Generated by the bstk-compat harness (TLS mode).\n\
         [[listener]]\n\
         addr = \"127.0.0.1:{port}\"\n\
         tls = true\n\
         auth = \"none\"\n\
         \n\
         [tls]\n\
         cert = {}\n\
         key = {}\n",
        toml_string(material.cert_path()),
        toml_string(material.key_path()),
    )
}

/// The stunnel configuration forwarding TLS on `front_port` to plaintext
/// on `back_port`.
pub fn stunnel_config(front_port: u16, back_port: u16, material: &TlsMaterial) -> String {
    format!(
        "; Generated by the bstk-compat harness (stunnel mode).\n\
         foreground = yes\n\
         pid =\n\
         syslog = no\n\
         debug = 6\n\
         socket = l:TCP_NODELAY=1\n\
         socket = r:TCP_NODELAY=1\n\
         \n\
         [bstk]\n\
         accept = 127.0.0.1:{front_port}\n\
         connect = 127.0.0.1:{back_port}\n\
         cert = {}\n\
         key = {}\n",
        material.cert_path().display(),
        material.key_path().display(),
    )
}

/// A TOML basic string holding `path`.
fn toml_string(path: &Path) -> String {
    let mut out = String::from("\"");
    for c in path.to_string_lossy().chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c if c.is_control() => out.push_str(&format!("\\u{:04X}", u32::from(c))),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// How to start a server: the binary, the case's extra arguments, whether
/// it gets its own binlog directory, and how it is exposed.
#[derive(Debug, Clone)]
pub struct ServerConfig<'a> {
    pub bin: &'a Path,
    pub extra_args: &'a [String],
    pub binlog: bool,
    pub transport: ServerTransport,
}

/// A running server process, spawned on a free `127.0.0.1` port. Killed and
/// reaped when dropped, so a panicking test never leaves an orphan process
/// behind. Its port is released from [`CLAIMED_PORTS`] and its binlog
/// directory (if any) is removed on drop as well. In stunnel mode the
/// stunnel process is owned (and killed) the same way.
pub struct ServerProcess {
    child: Child,
    /// The address clients connect to (stunnel's port in stunnel mode).
    addr: SocketAddr,
    /// The port the server process itself listens on (equal to
    /// `addr.port()` unless in stunnel mode).
    server_port: u16,
    bin: PathBuf,
    /// Full argument list after the listener arguments (`-l 127.0.0.1 -p
    /// <port>`, or `--config <file>` in TLS mode): the case's extra args
    /// plus `-b <dir>` when a binlog directory is used.
    args: Vec<String>,
    transport: ServerTransport,
    /// The stunnel process (stunnel mode only).
    proxy: Option<Child>,
    // Declared last so they are dropped after the processes have been
    // reaped (fields drop after `Drop::drop` runs).
    /// Generated configuration files and logs (TLS and stunnel modes).
    conf_dir: Option<TempDir>,
    binlog_dir: Option<BinlogDir>,
}

impl ServerProcess {
    /// The address clients connect to.
    pub fn addr(&self) -> SocketAddr {
        self.addr
    }

    /// How clients connect to this server.
    pub fn client_transport(&self) -> ClientTransport {
        self.transport.client()
    }

    /// OS process id of the server (target of `signal` steps). Changes
    /// after a restart. In stunnel mode, this is the server behind stunnel.
    pub fn pid(&self) -> u32 {
        self.child.id()
    }

    /// The binlog directory passed as `-b`, if any.
    pub fn binlog_dir(&self) -> Option<&Path> {
        self.binlog_dir.as_ref().map(BinlogDir::path)
    }

    fn launch(&self) -> Launch<'_> {
        Launch {
            bin: &self.bin,
            args: &self.args,
            transport: &self.transport,
            conf_dir: self.conf_dir.as_ref().map(TempDir::path),
        }
    }

    /// Stop the server (`Term`: SIGTERM, `Kill`: SIGKILL), wait for it to
    /// exit, sleep `downtime`, then start the same binary with the same
    /// arguments and binlog directory. The same port is reused when
    /// possible; otherwise a new one is claimed and [`Self::addr`] changes.
    /// In stunnel mode only the server behind stunnel is restarted; stunnel
    /// keeps its public port and is restarted (pointing at the new backend
    /// port) only if the backend had to move.
    pub fn restart(&mut self, how: StopMode, downtime: Duration) -> Result<(), SpawnError> {
        self.stop(how)?;
        std::thread::sleep(downtime);

        let port = self.server_port;
        let mut last_err = String::new();
        // First try the same port a few times (the old listener is gone
        // once the process has been reaped; servers use SO_REUSEADDR).
        for _ in 0..SPAWN_ATTEMPTS {
            match self.launch().start_on_port(port) {
                Ok(child) => {
                    self.child = child;
                    return Ok(());
                }
                Err(e) => last_err = e.0,
            }
        }
        // Fall back to a fresh port.
        for _ in 0..SPAWN_ATTEMPTS {
            let new_port = claim_free_port()
                .map_err(|e| SpawnError(format!("could not find a free port: {e}")))?;
            match self.launch().start_on_port(new_port) {
                Ok(child) => {
                    self.child = child;
                    release_port(port);
                    self.server_port = new_port;
                    if self.proxy.is_some() {
                        self.restart_proxy()?;
                    } else {
                        self.addr = ([127, 0, 0, 1], new_port).into();
                    }
                    return Ok(());
                }
                Err(e) => {
                    release_port(new_port);
                    last_err = e.0;
                }
            }
        }
        Err(SpawnError(format!(
            "server {} failed to restart: {last_err}",
            self.bin.display()
        )))
    }

    /// Stunnel mode: restart stunnel on the same public port, forwarding to
    /// the (new) backend port.
    fn restart_proxy(&mut self) -> Result<(), SpawnError> {
        if let Some(mut old) = self.proxy.take() {
            let _ = old.kill();
            let _ = old.wait();
        }
        let front = self.addr.port();
        let mut last_err = String::new();
        for _ in 0..SPAWN_ATTEMPTS {
            match self.launch().start_proxy(front, self.server_port) {
                Ok(child) => {
                    self.proxy = Some(child);
                    return Ok(());
                }
                Err(e) => last_err = e.0,
            }
        }
        Err(SpawnError(format!("stunnel failed to restart: {last_err}")))
    }

    fn stop(&mut self, how: StopMode) -> Result<(), SpawnError> {
        match how {
            StopMode::Kill => {
                self.child
                    .kill()
                    .map_err(|e| SpawnError(format!("SIGKILL failed: {e}")))?;
            }
            StopMode::Term => {
                // Via kill(1): keeps this crate free of `unsafe` and libc.
                let status = Command::new("kill")
                    .arg("-TERM")
                    .arg(self.child.id().to_string())
                    .status()
                    .map_err(|e| SpawnError(format!("failed to run kill: {e}")))?;
                if !status.success() {
                    return Err(SpawnError(format!("kill -TERM exited with {status}")));
                }
            }
        }
        let deadline = Instant::now() + STOP_TIMEOUT;
        loop {
            match self.child.try_wait() {
                Ok(Some(_)) => return Ok(()),
                Ok(None) => {}
                Err(e) => return Err(SpawnError(format!("wait failed: {e}"))),
            }
            if Instant::now() >= deadline {
                let _ = self.child.kill();
                let _ = self.child.wait();
                return Err(SpawnError(format!(
                    "server did not exit within {STOP_TIMEOUT:?} after {}",
                    how.directive()
                )));
            }
            std::thread::sleep(Duration::from_millis(10));
        }
    }
}

impl Drop for ServerProcess {
    fn drop(&mut self) {
        if let Some(proxy) = &mut self.proxy {
            let _ = proxy.kill();
            let _ = proxy.wait();
        }
        // Stunnel mode (the proxy may be gone after a failed restart).
        if self.addr.port() != self.server_port {
            release_port(self.addr.port());
        }
        let _ = self.child.kill();
        let _ = self.child.wait();
        release_port(self.server_port);
    }
}

#[derive(Debug)]
pub struct SpawnError(pub String);

impl std::fmt::Display for SpawnError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::error::Error for SpawnError {}

/// Spawn `bin` with `-l 127.0.0.1 -p <port>` plus `extra_args`, and block
/// until it accepts TCP connections (or the startup timeout elapses).
pub fn spawn_server(bin: &Path, extra_args: &[String]) -> Result<ServerProcess, SpawnError> {
    spawn(&ServerConfig {
        bin,
        extra_args,
        binlog: false,
        transport: ServerTransport::Plain,
    })
}

/// Spawn a server as described by `cfg`: like [`spawn_server`], plus a
/// fresh binlog directory passed as `-b <dir>` when `cfg.binlog` is set,
/// and exposed over `cfg.transport`.
pub fn spawn(cfg: &ServerConfig<'_>) -> Result<ServerProcess, SpawnError> {
    let bin = cfg.bin;
    if !bin.exists() {
        return Err(SpawnError(format!(
            "server binary not found: {}",
            bin.display()
        )));
    }
    if let ServerTransport::Stunnel { stunnel, .. } = &cfg.transport
        && !stunnel.exists()
    {
        return Err(SpawnError(format!(
            "stunnel binary not found: {}",
            stunnel.display()
        )));
    }

    let mut args = cfg.extra_args.to_vec();
    let binlog_dir = if cfg.binlog {
        let dir = BinlogDir::create()
            .map_err(|e| SpawnError(format!("could not create binlog directory: {e}")))?;
        args.push("-b".to_string());
        args.push(dir.path().to_string_lossy().into_owned());
        Some(dir)
    } else {
        None
    };
    let conf_dir = match cfg.transport {
        ServerTransport::Plain => None,
        ServerTransport::Tls(_) | ServerTransport::Stunnel { .. } => Some(
            TempDir::with_prefix("bstk-compat-conf")
                .map_err(|e| SpawnError(format!("could not create config directory: {e}")))?,
        ),
    };
    let launch = Launch {
        bin,
        args: &args,
        transport: &cfg.transport,
        conf_dir: conf_dir.as_ref().map(TempDir::path),
    };

    let mut last_err = String::new();
    for _ in 0..SPAWN_ATTEMPTS {
        let port = claim_free_port()
            .map_err(|e| SpawnError(format!("could not find a free port: {e}")))?;
        let mut child = match launch.start_on_port(port) {
            Ok(child) => child,
            Err(e) => {
                release_port(port);
                last_err = e.0;
                continue;
            }
        };
        let mut addr: SocketAddr = ([127, 0, 0, 1], port).into();
        let mut proxy = None;
        if matches!(cfg.transport, ServerTransport::Stunnel { .. }) {
            let front = claim_free_port()
                .map_err(|e| SpawnError(format!("could not find a free port: {e}")));
            let started = front.and_then(|front| {
                launch
                    .start_proxy(front, port)
                    .map(|p| (front, p))
                    .inspect_err(|_| release_port(front))
            });
            match started {
                Ok((front, p)) => {
                    addr = ([127, 0, 0, 1], front).into();
                    proxy = Some(p);
                }
                Err(e) => {
                    let _ = child.kill();
                    let _ = child.wait();
                    release_port(port);
                    last_err = e.0;
                    continue;
                }
            }
        }
        return Ok(ServerProcess {
            child,
            addr,
            server_port: port,
            bin: bin.to_path_buf(),
            args,
            transport: cfg.transport.clone(),
            proxy,
            conf_dir,
            binlog_dir,
        });
    }

    Err(SpawnError(format!(
        "server {} failed to start after {SPAWN_ATTEMPTS} attempts: {last_err}",
        bin.display()
    )))
}

/// Everything needed to (re)start a server process.
struct Launch<'a> {
    bin: &'a Path,
    args: &'a [String],
    transport: &'a ServerTransport,
    conf_dir: Option<&'a Path>,
}

impl Launch<'_> {
    fn conf_dir(&self) -> Result<&Path, SpawnError> {
        self.conf_dir
            .ok_or_else(|| SpawnError("internal error: no config directory".to_string()))
    }

    /// Start the server on `port` (already claimed by the caller) and wait
    /// until it serves requests. On failure the child is killed and reaped;
    /// the port stays claimed.
    fn start_on_port(&self, port: u16) -> Result<Child, SpawnError> {
        let addr: SocketAddr = ([127, 0, 0, 1], port).into();
        let mut cmd = Command::new(self.bin);
        let probe_transport = match self.transport {
            ServerTransport::Tls(material) => {
                let path = self.conf_dir()?.join(format!("server-{port}.toml"));
                std::fs::write(&path, tls_server_config(port, material))
                    .map_err(|e| SpawnError(format!("could not write {}: {e}", path.display())))?;
                cmd.arg("--config").arg(&path);
                self.transport.client()
            }
            // In stunnel mode the server itself is plaintext; probing it
            // directly keeps its connection count identical to a plaintext
            // server's (one probe connection).
            ServerTransport::Plain | ServerTransport::Stunnel { .. } => {
                cmd.arg("-l")
                    .arg("127.0.0.1")
                    .arg("-p")
                    .arg(port.to_string());
                ClientTransport::Plain
            }
        };
        cmd.args(self.args)
            .stdin(Stdio::null())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped());

        let mut child = cmd
            .spawn()
            .map_err(|e| SpawnError(format!("failed to spawn {}: {e}", self.bin.display())))?;

        match wait_until_accepting(&mut child, addr, STARTUP_TIMEOUT, &probe_transport) {
            Ok(()) => Ok(child),
            Err(e) => {
                let _ = child.kill();
                let _ = child.wait();
                Err(SpawnError(e))
            }
        }
    }

    /// Stunnel mode: start stunnel accepting TLS on `front_port` (claimed
    /// by the caller) and forwarding to `back_port`, and wait until it
    /// listens.
    ///
    /// Readiness is read from stunnel's log (`debug = 6` logs the successful
    /// bind of the service), never probed with a connection: any
    /// connection through stunnel would add one to the server's
    /// `total-connections`, and a TCP connect alone could reach an
    /// unrelated listener if stunnel failed to bind.
    fn start_proxy(&self, front_port: u16, back_port: u16) -> Result<Child, SpawnError> {
        let ServerTransport::Stunnel { stunnel, material } = self.transport else {
            return Err(SpawnError(
                "internal error: start_proxy outside stunnel mode".to_string(),
            ));
        };
        let dir = self.conf_dir()?;
        let conf = dir.join(format!("stunnel-{front_port}.conf"));
        std::fs::write(&conf, stunnel_config(front_port, back_port, material))
            .map_err(|e| SpawnError(format!("could not write {}: {e}", conf.display())))?;
        let log_path = dir.join(format!("stunnel-{front_port}.log"));
        let log = std::fs::File::create(&log_path)
            .map_err(|e| SpawnError(format!("could not create {}: {e}", log_path.display())))?;
        let log_err = log
            .try_clone()
            .map_err(|e| SpawnError(format!("could not clone log handle: {e}")))?;
        let mut child = Command::new(stunnel)
            .arg(&conf)
            .stdin(Stdio::null())
            .stdout(Stdio::from(log))
            .stderr(Stdio::from(log_err))
            .spawn()
            .map_err(|e| SpawnError(format!("failed to spawn {}: {e}", stunnel.display())))?;

        let deadline = Instant::now() + STARTUP_TIMEOUT;
        let bound = format!("bound to 127.0.0.1:{front_port}\n");
        let fail = |child: &mut Child, why: String| {
            let _ = child.kill();
            let _ = child.wait();
            let log = std::fs::read_to_string(&log_path).unwrap_or_default();
            SpawnError(format!("stunnel {why}; log={log:?}"))
        };
        loop {
            match child.try_wait() {
                Ok(Some(status)) => return Err(fail(&mut child, format!("exited with {status}"))),
                Ok(None) => {}
                Err(e) => return Err(fail(&mut child, format!("could not be waited for: {e}"))),
            }
            let log = std::fs::read_to_string(&log_path).unwrap_or_default();
            // "bound to" follows bind(); "Accepting new connections"
            // follows listen() and precedes the accept loop.
            if log.contains(&bound) && log.contains("Accepting new connections") {
                return Ok(child);
            }
            // stunnel keeps running (without any listener) when binding
            // fails, e.g. because the port was taken in the meantime.
            if log.contains("Binding service [bstk] failed") || log.contains("Configuration failed")
            {
                return Err(fail(&mut child, "failed to start".to_string()));
            }
            if Instant::now() >= deadline {
                return Err(fail(
                    &mut child,
                    format!("did not listen within {STARTUP_TIMEOUT:?}"),
                ));
            }
            std::thread::sleep(Duration::from_millis(10));
        }
    }
}

fn wait_until_accepting(
    child: &mut Child,
    addr: SocketAddr,
    timeout: Duration,
    transport: &ClientTransport,
) -> Result<(), String> {
    let deadline = Instant::now() + timeout;
    loop {
        if let Some(status) = child.try_wait().map_err(|e| e.to_string())? {
            let stderr = read_all(child.stderr.take());
            let stdout = read_all(child.stdout.take());
            return Err(format!(
                "server exited early with {status}; stderr={stderr:?} stdout={stdout:?}"
            ));
        }
        let remaining = deadline.saturating_duration_since(Instant::now());
        if probe_ready(addr, remaining.max(Duration::from_millis(500)), transport) {
            // The probe also sees EOF when the process died while it was
            // waiting (e.g. binlog lock held elsewhere); re-check.
            std::thread::sleep(Duration::from_millis(5));
            if child.try_wait().map_err(|e| e.to_string())?.is_none() {
                return Ok(());
            }
            continue;
        }
        if Instant::now() >= deadline {
            return Err(format!(
                "server did not accept connections within {timeout:?}"
            ));
        }
        std::thread::sleep(Duration::from_millis(20));
    }
}

/// Check readiness with a full request/response round trip (`quit`), not a
/// bare connect-then-drop: under heavy parallel load, a connection that is
/// accepted at the TCP level but abandoned by the client before the server
/// reads or writes anything can otherwise leave the freshly-spawned
/// process's event loop in a state where it stops accepting further
/// connections, causing every real client of that process to hang. Doing
/// one real command exchange exercises the same code path a real client
/// will use and avoids that class of startup race entirely.
///
/// Once the TCP connect succeeds, the probe waits up to `read_timeout` (the
/// rest of the startup budget) for the reply instead of giving up early and
/// retrying: the server may accept at the kernel level before it serves
/// (the reference binds its socket before replaying / preallocating the
/// binlog, which can take a while under load), and every retried probe
/// would count as one more `total-connections` on that side only.
///
/// Over TLS the probe is the same exchange on a TLS connection (a plaintext
/// `quit` would never complete against a TLS listener); it counts as one
/// connection as well.
fn probe_ready(addr: SocketAddr, read_timeout: Duration, transport: &ClientTransport) -> bool {
    use std::io::{Read, Write};
    if transport.is_tls() {
        let Ok(mut conn) = crate::conn::connect(addr, transport, Duration::from_millis(200)) else {
            return false;
        };
        if conn.send(b"quit\r\n").is_err() {
            return false;
        }
        return conn.recv_closed(read_timeout) == crate::conn::Outcome::Closed;
    }
    let Ok(mut stream) = TcpStream::connect_timeout(&addr, Duration::from_millis(200)) else {
        return false;
    };
    if stream.set_read_timeout(Some(read_timeout)).is_err() {
        return false;
    }
    if stream.write_all(b"quit\r\n").is_err() {
        return false;
    }
    // "quit" has no reply; a clean EOF (or simply not erroring) confirms the
    // server processed our command rather than merely accepting the socket.
    let mut buf = [0u8; 16];
    stream.read(&mut buf).is_ok()
}

fn read_all(pipe: Option<impl std::io::Read>) -> String {
    let Some(mut pipe) = pipe else {
        return String::new();
    };
    let mut buf = String::new();
    let _ = pipe.read_to_string(&mut buf);
    buf
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn binlog_dir_is_created_empty_and_removed_on_drop() {
        let dir = BinlogDir::create().expect("create");
        let path = dir.path().to_path_buf();
        assert!(path.is_dir());
        std::fs::write(path.join("binlog.1"), b"x").expect("write");
        let other = BinlogDir::create().expect("create");
        assert_ne!(other.path(), path);
        drop(dir);
        assert!(!path.exists());
    }

    /// Restart keeps the binlog directory and (normally) the port, and the
    /// directory is removed when the server is dropped. Uses the reference
    /// binary, which must exist (built by scripts/build-ref.sh).
    #[test]
    fn restart_keeps_binlog_dir_and_drop_removes_it() {
        let bin = crate::runner::default_ref_bin();
        assert!(bin.exists(), "reference binary missing: {}", bin.display());
        let mut server = spawn(&ServerConfig {
            bin: &bin,
            extra_args: &[],
            binlog: true,
            transport: ServerTransport::Plain,
        })
        .expect("spawn");
        let dir = server.binlog_dir().expect("binlog dir").to_path_buf();
        assert!(dir.is_dir());
        let pid = server.pid();
        for how in [StopMode::Term, StopMode::Kill] {
            server.restart(how, Duration::ZERO).expect("restart");
            assert_eq!(server.binlog_dir(), Some(dir.as_path()));
            assert!(probe_ready(
                server.addr(),
                Duration::from_secs(2),
                &ClientTransport::Plain
            ));
        }
        assert_ne!(server.pid(), pid);
        drop(server);
        assert!(!dir.exists());
    }

    #[test]
    fn tls_server_config_declares_one_tls_listener() {
        let m = TlsMaterial::generate().expect("generate");
        let text = tls_server_config(4321, &m);
        assert!(
            text.contains("[[listener]]\naddr = \"127.0.0.1:4321\"\ntls = true\nauth = \"none\"\n")
        );
        assert_eq!(text.matches("[[listener]]").count(), 1);
        assert!(text.contains(&format!("cert = \"{}\"", m.cert_path().display())));
        assert!(text.contains(&format!("key = \"{}\"", m.key_path().display())));
    }

    #[test]
    fn toml_string_escapes_quotes_and_backslashes() {
        assert_eq!(toml_string(Path::new("/a b/c")), "\"/a b/c\"");
        assert_eq!(toml_string(Path::new("/a\"b\\c")), "\"/a\\\"b\\\\c\"");
    }

    fn stunnel_server() -> Option<ServerProcess> {
        let Some(stunnel) = crate::runner::find_stunnel() else {
            eprintln!("skipping: no stunnel binary found");
            return None;
        };
        let bin = crate::runner::default_ref_bin();
        assert!(bin.exists(), "reference binary missing: {}", bin.display());
        let material = Arc::new(TlsMaterial::generate().expect("generate"));
        let server = spawn(&ServerConfig {
            bin: &bin,
            extra_args: &[],
            binlog: true,
            transport: ServerTransport::Stunnel { stunnel, material },
        })
        .expect("spawn behind stunnel");
        Some(server)
    }

    fn stats_line(conn: &mut crate::conn::ConnHandle, key: &str) -> String {
        conn.send(b"stats\r\n").expect("send");
        let crate::conn::Outcome::Received(resp) = conn.recv_response() else {
            panic!("no stats response");
        };
        let text = String::from_utf8(resp).expect("utf-8");
        text.lines()
            .find(|l| l.starts_with(&format!("{key}: ")))
            .unwrap_or_else(|| panic!("no {key} in stats"))
            .to_string()
    }

    /// Behind stunnel, the public port speaks TLS only, the backend sees
    /// exactly one connection per client connection (plus the plaintext
    /// readiness probe, like a plaintext server), and a restart keeps the
    /// public address.
    #[test]
    fn stunnel_mode_serves_tls_and_counts_connections_like_plaintext() {
        let Some(mut server) = stunnel_server() else {
            return;
        };
        let addr = server.addr();
        assert_ne!(addr.port(), server.server_port);

        // Plaintext on the public port gets no beanstalkd reply.
        let mut plain = crate::conn::connect(addr, &ClientTransport::Plain, STARTUP_TIMEOUT)
            .expect("plain connect");
        plain.send(b"stats\r\n").expect("send");
        assert!(!matches!(
            plain.recv_response(),
            crate::conn::Outcome::Received(r) if r.starts_with(b"OK ")
        ));
        drop(plain);

        let transport = server.client_transport();
        let mut conn = crate::conn::connect(addr, &transport, STARTUP_TIMEOUT).expect("connect");
        // The readiness probe, the rejected plaintext client (stunnel
        // never connected it to the backend) and this one.
        assert_eq!(
            stats_line(&mut conn, "total-connections"),
            "total-connections: 2"
        );
        assert_eq!(
            stats_line(&mut conn, "current-connections"),
            "current-connections: 1"
        );
        drop(conn);

        server
            .restart(StopMode::Kill, Duration::ZERO)
            .expect("restart");
        assert_eq!(server.addr(), addr);
        let mut conn = crate::conn::connect(addr, &transport, STARTUP_TIMEOUT).expect("connect");
        assert_eq!(
            stats_line(&mut conn, "total-connections"),
            "total-connections: 2"
        );
    }
}
